In [14]:
#Mathematic and scalar operations on arrays
import numpy as np

In [15]:
arr1 = np.array([[1,2,3,4],[6,7,8,9]])

In [16]:
arr1

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [17]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [36, 49, 64, 81]])

In [18]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [20]:
arr1 ** 3

array([[  1,   8,  27,  64],
       [216, 343, 512, 729]], dtype=int32)