In [2]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray',arr) #saves the array as and npy object

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.load('myarray.npy') #reloads the npy object

In [6]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.savez('ziparray.npz', x=arr1, y=arr2) #saves multi arrays as zip with x y attributes

In [10]:
z_arr = np.load('ziparray.npz')

In [12]:
z_arr['x']

array([0, 1, 2, 3, 4])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.savetxt('myarraytext.txt',arr,delimiter=',') # save as text file separated by a delimiter

In [27]:
arr = np.loadtxt('myarraytext.txt', delimiter=',') #reload the text file with the delimiter if specified
arr

array([[1., 2., 3.],
       [4., 5., 6.]])