In [30]:
import numpy as np

In [31]:
array1 = [1,2,3,4]

In [32]:
np_array = np.array(array1)

In [33]:
np_array

array([1, 2, 3, 4])

In [34]:
array2 = [11,12,13,14]

In [35]:
my_list = [array1, array2]

In [36]:
np_array = np.array(my_list)

In [37]:
np_array

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [38]:
np_array.shape

(2, 4)

In [39]:
np_array.dtype

dtype('int32')

In [40]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [44]:
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])