In [1]:
#Array indexing
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[4]

4

In [6]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
arr[0:5] = 777
arr

array([777, 777, 777, 777, 777,  50,  60,  70,  80,  90])

In [9]:
arr = np.arange(0,100,10)

In [10]:
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
slice_arr = arr[0:6]
slice_arr[:] = 999

In [19]:
arr

array([999, 999, 999, 999, 999, 999,  60,  70,  80,  90])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy

array([999, 999, 999, 999, 999, 999,  60,  70,  80,  90])

In [27]:
arr_2d = np.array(([5,10,15,20],[25,30,35,40],[45,50,55,60])) #create multi-dem array
arr_2d #show multi-dem array

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [28]:
arr_2d[1] # first row
arr_2d[1][0] # 1st index ie second row and first value

25

In [30]:
arr_2d[:2,1:] #everything beyong first 1st column and upto two rows

array([[10, 15, 20],
       [30, 35, 40]])

In [32]:
#fancy indexing
arr2d = np.zeros((5,5))
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
arr_len = arr2d.shape[1] #passing value will return length of that index row otherwise of entire matrix
arr_len

5

In [40]:
for i in range(arr_len): #manipulate elements of array
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [45]:
arr2d[0] = 9 # entire array row is changed to 9

In [48]:
arr2d[[4,2,3]] # can retrieve rows in any sequence

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])